/*
 * GCRSBaseConst.h
 *
 *  Created on: Aug 8, 2013
 *      Author: tony
 */

#ifndef GCRSBASECONST_H_
#define GCRSBASECONST_H_
#include <Consts80211p.h>
/*
 * Application Layer
 */
#define CON_APP_DEFAULT_HEADER_LENGTH 256
#define CON_APP_DEFAULT_VECTOR_SIZE 20
#define CON_APP_DEFAULT_CHECK_BUFFER_INTERVAL 1.0f
#define CON_APP_DEFAULT_BROADCAST_INTERVAL 0.5f
#define CON_APP_DEFAULT_PRIORITY_CLASS 3
#define CON_APP_DEFAULT_TTL 5.0f
#define CON_APP_DEFAULT_INDIVIDUAL_OFFSET 1.0f
/*
 * Network Layer
 */
#define CON_NET_DEFAULT_HEADER_LENGTH 32
//ZOR/ZOF shape
#define CON_NET_ZOR_ZOF_SHAPE_CIRCLE 0
#define CON_NET_ZOR_ZOF_SHAPE_RECTANGLE 1
#define CON_NET_ZOR_ZOF_SHAPE_ELLIPSE 2
#define CON_NET_DEFAULT_ZOR_SHAPE_RECTANGLE CON_NET_ZOR_ZOF_SHAPE_RECTANGLE
#define CON_NET_DEFAULT_ZOR_SHAPE_RECTANGLE_LENGTH 500
#define CON_NET_DEFAULT_ZOR_SHAPE_RECTANGLE_WIDTH 500
#define CON_NET_DEFAULT_ZOF_SHAPE_RECTANGLE CON_NET_ZOR_ZOF_SHAPE_RECTANGLE
#define CON_NET_DEFAULT_ZOF_SHAPE_RECTANGLE_LENGTH CON_NET_DEFAULT_ZOR_SHAPE_RECTANGLE_LENGTH + 150
#define CON_NET_DEFAULT_ZOF_SHAPE_RECTANGLE_WIDTH CON_NET_DEFAULT_ZOR_SHAPE_RECTANGLE_WIDTH
//Persistence Time
#define CON_NET_DEFAULT_PERSISTENCE_TIME_EPSILON 0.5f
#define CON_NET_DEFAULT_PERSISTENCE_TIME_MINCW  0.0f
#define CON_NET_DEFAULT_PERSISTENCE_TIME_MAXCW  0.002f

#endif /* GCRSBASECONST_H_ */
