//
// Generated file, do not edit! Created by opp_msgc 4.4 from src/modules/pkt/GCRSDTSGNetPkt.msg.
//

#ifndef _GCRSDTSGNETPKT_M_H_
#define _GCRSDTSGNETPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "GCRSBaseNetPkt_m.h"
// }}



/**
 * Class generated from <tt>src/modules/pkt/GCRSDTSGNetPkt.msg</tt> by opp_msgc.
 * <pre>
 * packet GCRSDTSGNetPkt extends GCRSBaseNetPkt{
 * 	bool preStableFlg = true;   
 * }
 * </pre>
 */
class GCRSDTSGNetPkt : public ::GCRSBaseNetPkt
{
  protected:
    bool preStableFlg_var;

  private:
    void copy(const GCRSDTSGNetPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GCRSDTSGNetPkt&);

  public:
    GCRSDTSGNetPkt(const char *name=NULL, int kind=0);
    GCRSDTSGNetPkt(const GCRSDTSGNetPkt& other);
    virtual ~GCRSDTSGNetPkt();
    GCRSDTSGNetPkt& operator=(const GCRSDTSGNetPkt& other);
    virtual GCRSDTSGNetPkt *dup() const {return new GCRSDTSGNetPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual bool getPreStableFlg() const;
    virtual void setPreStableFlg(bool preStableFlg);
};

inline void doPacking(cCommBuffer *b, GCRSDTSGNetPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GCRSDTSGNetPkt& obj) {obj.parsimUnpack(b);}


#endif // _GCRSDTSGNETPKT_M_H_
